Fix job detail crash when recommendations off
Without this, visiting any job detail page on Nomad OSS would
crash with an error like this:

Error: Ember Data Request GET /v1/recommendations?job=ping%F0%9F%A5%B3&namespace=default returned a 404
Payload (text/xml)

The problem was twofold. First, I made a copypaste error when
creating the recommendations ability: it shouldn’t include
bypassAuthorization, which is meant to skip permissions-checks
in the absence of ACLs. Second, I didn’t check permissions
at all in the job-fetching or job detail templates.

Thanks to @DingoEatingFuzz for catching this! 😯