Change to use npm build command
I don’t understand this build error:

Error: EACCES: permission denied, open '/home/travis/.config/configstore/ember-cli.json'
You don't have access to this file.

Do I need sudo???