The following test seems to show an issue in the GenericStack Select
While looking into a possible cause for issue #18567 I went through the HostVolume Feasible
check which seems to work fine, although both the CSI and HostVolume checks have
an empty Alloc.Name in the test cases, that shouldn't effectively change its behavior.
Anyway, I didn't find a problem in that code which could lead to the issue of incorrect
allocation placement. Next up I went looking into the Select method which sets all
iterator parameters including constraints and volumes. With the attached test I get
undeterministic results. Sometimes it passes, sometimes it fails with:

```
$ go test -count=1 -v -timeout 30s -tags darwin -run ^TestServiceStack_SelectHostVolume$ github.com/hashicorp/nomad/scheduler
=== RUN   TestServiceStack_SelectHostVolume
=== PAUSE TestServiceStack_SelectHostVolume
=== CONT  TestServiceStack_SelectHostVolume
--- PASS: TestServiceStack_SelectHostVolume (0.00s)
PASS
ok  	github.com/hashicorp/nomad/scheduler	0.244s

$ go test -count=1 -v -timeout 30s -tags darwin -run ^TestServiceStack_SelectHostVolume$ github.com/hashicorp/nomad/scheduler
=== RUN   TestServiceStack_SelectHostVolume
=== PAUSE TestServiceStack_SelectHostVolume
=== CONT  TestServiceStack_SelectHostVolume
    stack_test.go:370: missing node &structs.AllocMetric{NodesEvaluated:2, NodesFiltered:2, NodesInPool:0, NodesAvailable:map[string]int(nil), ClassFiltered:map[string]int{"linux-medium-pci":2}, ConstraintFiltered:map[string]int{"computed class ineligible":1, "missing compatible host volumes":1}, NodesExhausted:0, ClassExhausted:map[string]int(nil), DimensionExhausted:map[string]int(nil), QuotaExhausted:[]string(nil), ResourcesExhausted:map[string]*structs.Resources(nil), Scores:map[string]float64(nil), ScoreMetaData:[]*structs.NodeScoreMeta(nil), nodeScoreMeta:(*structs.NodeScoreMeta)(nil), topScores:(*kheap.ScoreHeap)(nil), AllocationTime:185208, CoalescedFailures:0}
--- FAIL: TestServiceStack_SelectHostVolume (0.00s)
FAIL
FAIL	github.com/hashicorp/nomad/scheduler	0.491s
FAIL
```

This to me looks like a bug, but going through the scheduler code is quite involved. It would
be great if someone can also have a look at this.