e2e: ui: fix playwright once and for all
I don't ever want to see this error again:

```
Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium_headless_shell-1193/chrome-linux/headless_shell
╔══════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just updated to 1.55.1. ║
║ Please update docker image as well.                                  ║
║ -  current: mcr.microsoft.com/playwright:v1.55.0-jammy               ║
║ - required: mcr.microsoft.com/playwright:v1.55.1-jammy               ║
║                                                                      ║
║ <3 Playwright Team                                                   ║
╚══════════════════════════════════════════════════════════════════════╝

   at global-setup.js:20

  18 |   }
  19 |
> 20 |   const browser = await chromium.launch();
     |                                  ^
  21 |   const context = await browser.newContext({ ignoreHTTPSErrors: true });
  22 |   const page = await context.newPage();
  23 |   await page.goto(NOMAD_ADDR+'/ui/settings/tokens');
    at module.exports (/src/global-setup.js:20:34)
```