client: fix unchanged devices causing node updates (#27363)
* test DevicesEquals

* fix the bug:
$ go test ./nomad/structs/ -run DevicesEquals
--- FAIL: TestDevicesEquals (0.00s)
    structs_test.go:6441:
        structs_test.go:6441: expected condition to be true; is false
        ↪ PostScript | annotation ↷
                unchanged copy should be equal

* add attribute to example device plugin

* add changelog